# Generated by Django 4.0.6 on 2022-09-06 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_post_options_likepost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likepost',
            options={'verbose_name': 'پسندیدن', 'verbose_name_plural': 'پسندیدن\u200cها'},
        ),
        migrations.AlterUniqueTogether(
            name='likepost',
            unique_together={('post', 'user')},
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='دنبال\u200cکننده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دنبال کننده',
                'verbose_name_plural': 'دنبال کنندگان',
                'unique_together': {('user', 'follower')},
            },
        ),
    ]
